### ISSUE TITLE
EPEL repository is not required on RHEL7

### ISSUE THREAD

**Issue by m8ram** [jtyr/ansible-open_vm_tools#1]
Hi,

This role will enable the EPEL repo on all systems.
in RHEL7 open-vm-tools is part of the rhel-7-server-rpms repo so it is not necessary to enable EPEL.

Is it possible to add a conditional so that EPEL is added only on RHEL5 and RHEL6?

TIA

**Comment by jtyr** [comment]
Such option is already there. Just set `open_vm_tools_epel_install: yes` and the creation of the EPEL repo will be skipped.
